title: CICN, Silicon University, Odisha
description: Center for Nanodevices, Integrated Circuits and Systems at Silicon University, Odisha, India is Center of Excellence for training and research in the area of CMOS Integrated Circuits, Semiconductor Devices and Electronic Systems.

theme: null

#url: 
#baseurl: 
lang: en
direction: auto

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
